name: Saludo usando variables

run-name: ¡Estoy aprendiendo a usar Variables y Secretos!

on:
  workflow_dispatch

env:
  DIA_DE_SEMANA: Lunes

jobs:
  saludo-variables:
    runs-on: ubuntu-latest

    env:
      SALUDO: Hola

    steps:
      - name: Saludar
        run: echo "$SALUDO, $NOMBRE. Hoy es $DIA_DE_SEMANA!"
        env:
          NOMBRE: Laura

  saludo-secreto:
    runs-on: ubuntu-latest

    steps:
      - name: Usar un secreto
        run: |
          echo "Estoy usando un secreto de GitHub Actions"
          echo "El valor del secreto está protegido por GitHub"
          echo "Mi contrasena es: ${{ secrets.CONTRASENA }}"
